### ISSUE TITLE
AIO LOADER HOW TO CONNECT PS3

### ISSUE THREAD

**Issue by Vape88Mods** [HerbL27/AIO-Loader#1]
How can i connect no button or other

https://imgur.com/a/GLiiiLW

**Comment by HerbL27** [comment]
It looks like the program is still updating the mods, but once the status changes to 'Ready' you can either upload pre-installed or custom mods. So connection is only made when uploading the files. 

**Pre-Installed**
Choose a game and your region, then choose one of the mods and click 'Install Mods'. Done.

**Custom**
Enable 'Custom' checkbox, then click '...' to open your mods file. Enter the installation path and click 'Install Mods'. Done.
